[pytest]
testpaths =
    tests/mock
    tests/live
python_files =
    test_*.py
python_classes =
    Test*
python_functions =
    test_*
asyncio_mode = auto
norecursedirs =
    .git
    .pytest_cache
    __pycache__
    tests/shared
    tests/unit
    tests/integration
addopts =
    -ra
